repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: debug-statements
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3
        args:
          - --target-version=py310
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.243
    hooks:
      - id: ruff
        args: [--show-source, --fix]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      -   id: codespell
          types_or: [rst, markdown]
          files: docs
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.1
    hooks:
      - id: mypy
        # Override default --ignore-missing-imports
        # Use setup.cfg if possible instead of adding command line parameters here
        args: [--warn-unused-configs]
        additional_dependencies:
          # Type stubs
          - pandas-stubs==v1.5.3.230227
          - types-requests
          - numpy
